//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.20 at 10:30:06 PM IST 
//


package com.emc.userregistrations.alluserservices;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.emc.userregistrations.alluserservices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetAllUserRequest_QNAME = new QName("http://com/emc/userRegistrations/AllUserServices", "GetAllUserRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.emc.userregistrations.alluserservices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllUserResponse }
     * 
     */
    public GetAllUserResponse createGetAllUserResponse() {
        return new GetAllUserResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com/emc/userRegistrations/AllUserServices", name = "GetAllUserRequest")
    public JAXBElement<Object> createGetAllUserRequest(Object value) {
        return new JAXBElement<Object>(_GetAllUserRequest_QNAME, Object.class, null, value);
    }

}
